- itu-minitwit-node/src/routes/index.js
- itu-minitwit-node/src/routes/signin.js
- itu-minitwit-node/src/views/layout.jade
- itu-minitwit-node/src/views/signin.jade
- itu-minitwit-node/src/views/signup.jade
-seen during group work with Matej and Ingrid
> W4 signup page

- itu-minitwit-node/app.js
- itu-minitwit-node/package-lock.json
- itu-minitwit-node/package.json
- itu-minitwit-node/src/db/dbService.js
- itu-minitwit-node/src/model/user.js
- itu-minitwit-node/src/routes/simulator.js
- itu-minitwit-node/src/services/LatestService.js
- itu-minitwit-node/src/utils/authorizationValidator.js
- itu-minitwit-node/src/utils/hash.js
Reverts ingrid-mc/DevOps-group_s#55
> Revert "Revert "W4 add endpoints for simulator""

- itu-minitwit-node/src/routes/message.js
- itu-minitwit-node/src/views/timeline.jade
> fixed date

- itu-minitwit-node/app.js
- itu-minitwit-node/package-lock.json
- itu-minitwit-node/package.json
Logger with rotating file stream module implemented
> added a logger

- .gitignore
now ignores all .dll and .DS_Store files
> some additions to the gitignore

- itu-minitwit-node/src/db/dbService.js
Intent to avoid error:
"mysql2 Can't add new command when connection is in closed state 0|minitwit | at Connection._addCommandClosedState"
> switch connections to pools

- itu-minitwit-node/app.js
- itu-minitwit-node/package-lock.json
- itu-minitwit-node/package.json
- itu-minitwit-node/src/db/dbService.js
- itu-minitwit-node/src/logger/logger.js
- itu-minitwit-node/src/metrics/metrics.js
- itu-minitwit-node/src/routes/follow.js
- itu-minitwit-node/src/routes/index.js
- itu-minitwit-node/src/routes/message.js
- itu-minitwit-node/src/routes/signin.js
- itu-minitwit-node/src/routes/signout.js
- itu-minitwit-node/src/routes/signup.js
- itu-minitwit-node/src/routes/simulator.js
- itu-minitwit-node/src/routes/unfollow.js
- itu-minitwit-node/src/routes/user.js
Major PR that adds more metrics to be displayed in Grafana.
MySQL query latency (histogram)
MySQL errors counter
MySQL health check
Minitwit HTTP error counters by code and endpoint
Minitwit HTTP request latency (histogram)
Minitwit health check
It also improves logging and error handling in every endpoint.
Other fixes:
- Some response messages were misleading and showed internal information. For instance, when the error was at the dba level, we returned information about our infrastructure, which is never recommended for security reasons.
- Removes the http-errors library that was not being used correctly
- Extracts Prometheus metrics to a different file, which gives a cleaner look to app.js and increases readability
> Improved grafana + logging correction

- itu-minitwit-node/src/views/timeline.jade
Very small PR that fixes time and date mismatch in public timeline + date formatting
> fixes time mismatch and format

- itu-minitwit-node/src/model/user.js
- itu-minitwit-node/src/routes/index.js
- itu-minitwit-node/src/routes/message.js
- itu-minitwit-node/src/routes/simulator.js
Improves queries by doing syntax optimization and avoiding querying whole tables
> Database optimization

- itu-minitwit-node/src/model/user.js
- itu-minitwit-node/src/routes/simulator.js
Reverts ingrid-mc/DevOps-group_s#140
> Revert " Database-small-optimization"

- itu-minitwit-node/src/routes/index.js
- itu-minitwit-node/src/routes/signin.js
- signing takes you to your timeline
- query for "my timeline" is optimized
> optimizing the query

- itu-minitwit-node/app.js
- itu-minitwit-node/package.json
- itu-minitwit-node/src/db/dbService.js
- itu-minitwit-node/src/db/session.js
- itu-minitwit-node/src/routes/index.js
- itu-minitwit-node/src/routes/simulator.js
- itu-minitwit-node/src/services/LatestService.js
There are two new tables called:
- sessions
- latest
I didn't confirm 100% that the session is not retrieved from the app's memory (It shouldn't)
> Stateless Latest and Session

- .github/workflows/continous-deployment.yml
- itu-minitwit-node/package.json
- itu-minitwit-node/src/model/followers.js
- itu-minitwit-node/src/model/user.js
- itu-minitwit-node/src/routes/index.js
- itu-minitwit-node/src/routes/signin.js
- itu-minitwit-node/src/routes/simulator.js
- itu-minitwit-node/src/utils/convertTime.js
- itu-minitwit-node/src/utils/gravatar.js
- itu-minitwit-node/src/views/timeline.jade
- itu-minitwit-node/tests/Dockerfile
- itu-minitwit-node/tests/LatestService.test.js
- itu-minitwit-node/tests/authorizationValidator.test.js
- itu-minitwit-node/tests/fllws-username.test.js
- itu-minitwit-node/tests/getLatest.test.js
- itu-minitwit-node/tests/gravatar.test.js
- itu-minitwit-node/tests/hash.test.js
- itu-minitwit-node/tests/msgs-username.test.js
- itu-minitwit-node/tests/msgs.test.js
- itu-minitwit-node/tests/register.test.js
Branch that recovers the changes that I lost during a bad move
> Recover branch

- itu-minitwit-node/app.js
- itu-minitwit-node/package.json
after a OWASP ZAP analysis, I fixed on of the vulnerabilities: "Server Leaks Information via "X-Powered-By" HTTP Response Header Field(s)". 
Adding this "Helmet" package sets header responses, which makes them more secure. As far as I understand I only needed to add two lines of code.
> fix header vulnerability

- itu-minitwit-node/cypress.config.js
- itu-minitwit-node/cypress/Dockerfile
- itu-minitwit-node/cypress/e2e/follow-unfollow.cy.js
- itu-minitwit-node/cypress/e2e/personal-timeline.cy.js
- itu-minitwit-node/cypress/e2e/public-timeline.cy.js
- itu-minitwit-node/cypress/e2e/sign-in.cy.js
- itu-minitwit-node/cypress/e2e/sign-up.cy.js
- itu-minitwit-node/cypress/support/commands.js
- itu-minitwit-node/cypress/support/e2e.js
- itu-minitwit-node/package.json
Cypress e2e tests added. A bit tricky to test, since it needs the application to run, and it can't because the DB is down. Would be a shame not to have as a part of the project, but also a little risky to push to main without you guys being able to check it. On the other hand, it can't do any harm, as it's not added to the CI/CD in this PR and the tests potentially accessing the db is commented out, so even if it doesn't work, it won't break anything.
> Cypress test final

- docs/Postmortems.md
Postmortems document updated in /docs folder
> postmortems

- .github/workflows/continous-integration.yml
Minor change - mostly for sake of logic
> New order in CI chain

- itu-minitwit-node/.eslintignore
- itu-minitwit-node/.eslintrc.js
- itu-minitwit-node/app.js
- itu-minitwit-node/package.json
- itu-minitwit-node/src/routes/follow.js
- itu-minitwit-node/src/routes/index.js
- itu-minitwit-node/src/routes/message.js
- itu-minitwit-node/src/routes/signin.js
- itu-minitwit-node/src/routes/signout.js
- itu-minitwit-node/src/routes/signup.js
- itu-minitwit-node/src/routes/simulator.js
- itu-minitwit-node/src/routes/unfollow.js
- itu-minitwit-node/src/routes/user.js
- itu-minitwit-node/tests/LatestService.test.js
- itu-minitwit-node/tests/fllws-username.test.js
- itu-minitwit-node/tests/gravatar.test.js
- itu-minitwit-node/tests/msgs-username.test.js
cleaning the code based on eslint warnings
> Playground

- sla.md
> changes to sla, test resources

- itu-minitwit-node/app.js
Updated changes, without package lock pushed
> changed helmet package to handle gravatars

- .github/workflows/continous-deployment.yml
- itu-minitwit-node/app.js
> header protection and manual trigger on cd added
